export const UPDATE_CODE = 'UPDATE_CODE';
export const LOAD_FILE = 'LOAD_FILE';
export const SAVE_FILE = 'SAVE_FILE';

export const EDITOR_LOADING = 'EDITOR_LOADING';

export const EXPORT_PDF = 'EXPORT_PDF';
export const EXPORT_PDF_COMPLETE = 'EXPORT_PDF_COMPLETE';
export const EXPORT_PDF_FAILED = 'EXPORT_PDF_FAILED';

export const PRESENTATION_MODE = 'PRESENTATION_MODE';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';

export const WILL_QUIT = 'WILL_QUIT';
export const QUIT_CANCELLED = 'QUIT_CANCELLED';

export const WINDOW_CLOSED = 'WINDOW_CLOSED';
